export const LOADING_NEARBY_SHOPS = 'LOADING_NEARBY_SHOPS';
export const FETCH_NEARBY_SHOPS = 'FETCH_NEARBY_SHOPS';
export const FETCH_MORE_NEARBY_SHOPS = 'FETCH_MORE_NEARBY_SHOPS';
export const FETCH_PREFERRED_SHOPS = 'FETCH_PREFERRED_SHOPS';
export const CLEAN_NEARBY_SHOPS_LIST = 'CLEAN_NEARBY_SHOPS_LIST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LIKE_DISLIKE_SHOP = 'LIKE_DISLIKE_SHOP';

