export const LOADING_NEARBY_SHOPS = 'LOADING_NEARBY_SHOPS';
export const FETCH_NEARBY_SHOPS = 'FETCH_NEARBY_SHOPS';
export const FETCH_MORE_NEARBY_SHOPS = 'FETCH_MORE_NEARBY_SHOPS';
export const FETCH_PREFERRED_SHOPS = 'FETCH_PREFERRED_SHOPS';
export const CLEAN_NEARBY_SHOPS_LIST = 'CLEAN_NEARBY_SHOPS_LIST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LIKE_DISLIKE_SHOP = 'LIKE_DISLIKE_SHOP';
export const FETCH_MORE_PREFERRED_SHOPS = 'FETCH_MORE_PREFERRED_SHOPS';
export const LOADING_PREFERRED_SHOPS = 'LOADING_PREFERRED_SHOPS';
export const CLEAN_PREFERRED_SHOPS_LIST = 'CLEAN_PREFERRED_SHOPS_LIST';
export const REMOVE_SHOP = 'REMOVE_SHOP';
export const ERRORS_REGISTER = 'ERRORS_REGISTER';
export const CLEAN_ERRORS_REGISTER = 'CLEAN_ERRORS_REGISTER';
export const ERRORS_LOGIN = 'ERRORS_LOGIN';
export const CLEAN_ERRORS_LOGIN = 'CLEAN_ERRORS_LOGIN';

